services:
  # FastAPI
  app:
    build:
      context: ./api
      dockerfile: Dockerfile.api.dev
    container_name: fastapi-app
    volumes:
      - ./api:/app
      - ./requirements:/app/requirements
    ports:
      - "8000:8000"
    env_file:
      - ./api/.env
    depends_on:
      - db

  # React UI
  ui:
    build:
      context: ./ui
      dockerfile: Dockerfile.ui.dev
    container_name: ui
    ports:
      - "3101:3101"
    volumes:
      - ./ui:/app:cached
      - /app/node_modules
    depends_on:
      - app

  # React Admin
  ui-admin:
    build:
      context: ./ui-admin
      dockerfile: Dockerfile.ui-admin.dev
    container_name: ui-admin
    ports:
      - "3102:3102"
    volumes:
      - ./ui-admin:/app:cached
      - /app/node_modules
    depends_on:
      - app

  # Postgres
  db:
    image: postgres:15
    container_name: fastapi-db
    restart: always
    env_file:
      - ./api/.env
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
